version: "3.7"
services:
  jacson-uat:
    container_name: jacson-uat-static-test
    build:
      context: /root/storefront-static-test/
      dockerfile: /root/storefront-static-test/docker/Dockerfile-uat
    ports:
      - 3005:3000
    restart: on-failure:5
