version: "3.7"
services:
  jacson-uat:
    container_name: jacson-uat
    build:
      context: /root/storefront/
      dockerfile: /root/storefront/docker/Dockerfile-uat
    ports:
      - 3005:3000
    restart: on-failure:5
